ALTER TABLE persons ALTER COLUMN birthday DROP NOT NULL;
ALTER TABLE persons ADD COLUMN IF NOT EXISTS is_owner BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS idx_persons_owner ON persons(user_id) WHERE is_owner = TRUE;
